<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2012-09-19 at 18:28:02.
 */
class UserControllerTest extends CTestCase {

    function setUp() {
        parent::setUp();
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * Api login and logaut
     * @covers UserController::actionAuth
     * @covers UserController::actionDeleteAuth
     * @covers UserController::actionPostAuth
     * @covers UserApi
     */
    public function testActionAuth() {
        $id     = Yii::app()->getParams()->api['user_id'];
        $puid   = Yii::app()->getParams()->api['user_puid'];
        $suid   = Yii::app()->getParams()->api['suid'];
        $model  = new UserApi();
        
        //логаут для чистоты эксперимента
        $responce = $model->deleteAuth($puid, array('key' => $suid));
        $this->assertTrue($responce->content->success);
        
        //проверка на авторизованность
        $this->assertTrue(!$this->checkAuth($puid, $suid)->auth);
        
        //логин
        $this->assertEquals($puid, $model->postAuth($suid, array('login' => 'login', 'paswd' => 'paswd'))->content->puid);
        
        //проверка на авторизованность
        $this->assertEquals($id, $this->checkAuth($puid, $suid)->id, 'Return not actual id.');
        
        //логаут
        $responce = $model->deleteAuth($puid, array('key' => $suid));
        $this->assertTrue($responce->content->success);
        
        //проверка на авторизованность
        $this->assertTrue(!$this->checkAuth($puid, $suid)->auth);
    }
    
    private function checkAuth($puid, $suid){
        $model = new UserApi();
        $responce = $model->getAuth($suid, array('puid' => $puid));
        return $responce->content;
    }

}
